#!/bin/bash

# A script that will ask for a value and print out a message depending on the value. 

read -p "Enter a value: " n

case $n in
    1|2) 
        echo "One or Two";;
    [3-9]*) 
        echo "Number 3 through 9";;
    ??) 
        echo "Two Characters";;
    *.txt) 
        echo "Ends in .txt";;
    *) 
        echo "Other";;
esac

    